# Generated by Django 4.1.6 on 2023-04-07 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_admin_department_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='课程号')),
                ('course_name', models.CharField(max_length=30, verbose_name='课程名称')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('title', models.TextField(verbose_name='题目')),
                ('question_tpye', models.TextField(default='单选题', verbose_name='题目类型')),
                ('question_item', models.IntegerField(default=4, verbose_name='选项数')),
                ('a', models.CharField(max_length=40, verbose_name='A选项')),
                ('b', models.CharField(max_length=40, verbose_name='B选项')),
                ('c', models.CharField(max_length=40, verbose_name='C选项')),
                ('d', models.CharField(max_length=40, verbose_name='D选项')),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=4, verbose_name='答案')),
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('middle', '中等'), ('difficult', '难')], max_length=10, verbose_name='难度')),
                ('score', models.IntegerField(verbose_name='分值')),
                ('correct', models.CharField(max_length=40, verbose_name='正确答案')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.course', verbose_name='学科')),
            ],
            options={
                'verbose_name': '题库',
                'verbose_name_plural': '题库',
            },
        ),
        migrations.AlterField(
            model_name='admin',
            name='phone',
            field=models.IntegerField(verbose_name='电话'),
        ),
        migrations.CreateModel(
            name='TestPaper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('paper_type', models.CharField(max_length=256, verbose_name='试卷类型')),
                ('title', models.CharField(max_length=40, unique=True, verbose_name='题目')),
                ('time', models.IntegerField(help_text='单位是分钟', verbose_name='考试时长')),
                ('examtime', models.DateTimeField(verbose_name='考试时间')),
                ('score', models.IntegerField(verbose_name='总分')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.course', verbose_name='科目')),
                ('pid', models.ManyToManyField(to='app01.questionbank')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('grade', models.FloatField(verbose_name='学生得分')),
                ('answer', models.CharField(max_length=64, verbose_name='学生答案')),
                ('correct', models.CharField(max_length=64, verbose_name='正确答案')),
                ('c_time', models.DateTimeField(verbose_name='记录时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_course', to='app01.course', verbose_name='考试科目')),
                ('paper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_paper', to='app01.testpaper', verbose_name='试卷')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_question', to='app01.questionbank', verbose_name='考试题目')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_id', to='app01.user', verbose_name='学号')),
            ],
            options={
                'verbose_name': '学生成绩',
                'verbose_name_plural': '学生成绩',
            },
        ),
    ]
