# Generated by Django 4.1.6 on 2023-04-22 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_rename_course_record_course_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='question_id',
        ),
    ]
