# Generated by Django 4.1.6 on 2023-04-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_rename_course_id_record_course_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='Record1',
        ),
    ]
