# Generated by Django 4.1.6 on 2023-04-22 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_record_delete_urecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stu_question', to='app01.questionbank', verbose_name='题目'),
            preserve_default=False,
        ),
    ]
