# Generated by Django 4.1.6 on 2023-04-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_record_delete_urecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, null=True, verbose_name='性别'),
        ),
    ]
