# Generated by Django 4.1.6 on 2023-04-23 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='sid',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_id', to='app01.user', verbose_name='学号'),
        ),
    ]
