# Generated by Django 4.1.6 on 2023-04-23 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_alter_record_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='course',
            field=models.ForeignKey(default='200111', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_course', to='app01.course', verbose_name='考试科目'),
        ),
        migrations.AlterField(
            model_name='record',
            name='paper',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_paper', to='app01.testpaper', verbose_name='试卷'),
        ),
        migrations.AlterField(
            model_name='record',
            name='sid',
            field=models.ForeignKey(default=4, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_id', to='app01.user', verbose_name='学号'),
        ),
    ]
