# Generated by Django 4.1.6 on 2023-04-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_alter_record_course_alter_record_paper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='course',
            field=models.CharField(default='200211', max_length=64, null=True, verbose_name='考试科目'),
        ),
        migrations.AlterField(
            model_name='record',
            name='paper',
            field=models.IntegerField(default=1, null=True, verbose_name='试卷'),
        ),
        migrations.AlterField(
            model_name='record',
            name='sid',
            field=models.IntegerField(default=4, null=True, verbose_name='学号'),
        ),
    ]
