# Generated by Django 4.1.6 on 2023-04-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_alter_record_course_alter_record_paper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='grade',
            field=models.FloatField(default=0, null=True, verbose_name='学生得分'),
        ),
    ]
