# Generated by Django 4.1.6 on 2023-04-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0023_questionbank_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('sid', models.IntegerField(default=4, verbose_name='学号')),
                ('paper', models.IntegerField(default=1, verbose_name='试卷')),
                ('num', models.IntegerField(verbose_name='题目数量')),
                ('grade', models.IntegerField(verbose_name='学生得分')),
                ('score', models.IntegerField(verbose_name='总分')),
            ],
        ),
    ]
