# Generated by Django 4.1.6 on 2023-04-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0024_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='paper',
            field=models.CharField(max_length=64, verbose_name='试卷'),
        ),
    ]
