# Generated by Django 4.1.6 on 2023-04-30 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0028_record_s_grade_alter_record_c_time_delete_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('answer', models.CharField(default=0, max_length=64, null=True, verbose_name='学生答案')),
                ('grade', models.FloatField(default=0, null=True, verbose_name='学生得分')),
                ('c_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='记录时间')),
                ('correct', models.CharField(max_length=40, null=True, verbose_name='正确答案')),
                ('course', models.ForeignKey(default='200211', on_delete=django.db.models.deletion.CASCADE, related_name='stu_course', to='app01.course', verbose_name='考试科目')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_paper', to='app01.testpaper', verbose_name='题目')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_question', to='app01.questionbank', verbose_name='题目')),
                ('sid', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='stu_id', to='app01.user', verbose_name='学号')),
            ],
            options={
                'verbose_name': '学生成绩',
                'verbose_name_plural': '学生成绩',
            },
        ),
        migrations.DeleteModel(
            name='record',
        ),
    ]
