# Generated by Django 4.1.6 on 2023-05-10 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0030_alter_urecord_paper_alter_urecord_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='知识点')),
                ('skill_name', models.CharField(max_length=30, verbose_name='知识点名称')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.course', verbose_name='学科')),
            ],
            options={
                'verbose_name': '知识点',
                'verbose_name_plural': '知识点',
            },
        ),
    ]
