# Generated by Django 4.1.6 on 2023-05-10 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0031_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='skills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.skill', verbose_name='知识点'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='知识点'),
        ),
    ]
